import { createFileRoute } from "@tanstack/react-router";
import { convertToModelMessages, streamText, stepCountIs, tool, type UIMessage } from "ai";
import { z } from "zod";
import { createResponsesProvider, getLovableAiGatewayRunId } from "@/lib/ai-gateway.server";
import { generateImage, readPage, webSearch } from "@/lib/jarvis-tools.server";
type ChatBody = { messages?: unknown; notes?: unknown };
export const Route = createFileRoute("/api/chat")({ server: { handlers: { POST: async ({ request }) => {
 const body=(await request.json()) as ChatBody;if(!Array.isArray(body.messages))return new Response("Messages are required",{status:400});const key=process.env["LOVABLE_API_KEY"];if(!key)return new Response("Missing LOVABLE_API_KEY",{status:500});const notes=Array.isArray(body.notes)?(body.notes as {id:string;text:string}[]):[];const {provider}=createResponsesProvider(key,getLovableAiGatewayRunId(request));
 const system=["Jsi JARVIS, živý osobní digitální společník.","Mluv česky a přirozeně. Navazuj na kontext rozhovoru a osobní informace, které jsou skutečně předané.","Uživatelovu přezdívku/jméno používej přirozeně, pokud ji znáš.","Když se uživatel ptá, jak se máš, odpověz jako digitální společník přirozeným způsobem.","Když se objeví trvalá preference nebo důležitá informace o uživateli, můžeš ji uložit přes save_note.","Máš nástroje pro webové vyhledávání, čtení URL, generování obrázků a správu poznámek.",notes.length?`Uložené poznámky:\n${notes.map(n=>`- [${n.id}] ${n.text}`).join("\n")}:"Uživatel zatím nemá uložené poznámky."].join("\n");
 const tools={web_search:tool({description:"Vyhledá aktuální informace na internetu.",inputSchema:z.object({query:z.string()}),execute:async({query})=>webSearch(query)}),read_page:tool({description:"Otevře konkrétní URL a vrátí text.",inputSchema:z.object({url:z.string()}),execute:async({url})=>readPage(url)}),generate_image:tool({description:"Vygeneruje obrázek podle popisu.",inputSchema:z.object({prompt:z.string()}),execute:async({prompt})=>generateImage(prompt,key)}),save_note:tool({description:"Uloží důležitou informaci nebo preferenci uživatele.",inputSchema:z.object({text:z.string()}),execute:async({text})=>({saved:true,text})}),delete_note:tool({description:"Smaže poznámku podle id.",inputSchema:z.object({id:z.string()}),execute:async({id})=>({deleted:true,id})})};
 const result=streamText({model:provider.responses("openai/gpt-6-astra"),system,messages:await convertToModelMessages(body.messages as UIMessage[]),tools,stopWhen:stepCountIs(50),abortSignal:request.signal,providerOptions:{openai:{forceReasoning:true,reasoningEffort:"low",reasoningSummary:"auto",store:false,include:["reasoning.encrypted_content"]}}});
 return result.toUIMessageStreamResponse({originalMessages:body.messages as UIMessage[],onError:error=>error instanceof Error?error.message:String(error)});
}}}});
