/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiImageIdRouteImport } from './routes/api/image.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageIdRoute = ApiImageIdRouteImport.update({
  id: '/api/image/$id',
  path: '/api/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/image/$id': typeof ApiImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/image/$id': typeof ApiImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/image/$id': typeof ApiImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/speak' | '/api/image/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/speak' | '/api/image/$id'
  id: '__root__' | '/' | '/api/chat' | '/api/speak' | '/api/image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiImageIdRoute: typeof ApiImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$id': {
      id: '/api/image/$id'
      path: '/api/image/$id'
      fullPath: '/api/image/$id'
      preLoaderRoute: typeof ApiImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiImageIdRoute: ApiImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
